language: elixir
elixir:
  - 1.7.3
otp_release:
  - '21.0'
addons:
  postgresql: '9.6'

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

env:
  global:
    - MIX_ENV=test
    - DATABASE_NAME=travis_ci_test
    - SECRET_KEY_BASE=tn0eZZr56FsC1BdBmQt8y5UzmUFDd2aQx0/ZnY/NgPW0ZZiboK6bDJK0GUOujslH
  matrix:
    - TEST_FOLDER=. FORMAT=1
    - TEST_FOLDER=./apps/golgotha
    - TEST_FOLDER=./apps/golgotha_web

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd $TEST_FOLDER
  - mix compile --warnings-as-errors
  - mix ecto.migrate
script:
  - mix test
  - if [ -z "$FORMAT" ]; then echo "Format check skipped"; else mix format --check-formatted --dry-run; fi

